openapi: "3.0.0"

info:
  version: 1.0.0
  title: OpenTestData
  license:
    name: MIT

paths:
  /ping:
    $ref: 'base.yaml#/paths/Ping'
  /users:
    $ref: 'users.yaml#/paths/SignUp'
  /users/login:
    $ref: 'users.yaml#/paths/Login'
  /users/resend_confirmation_email:
    $ref: 'users.yaml#/paths/EmailResend'
  /users/confirm_email/{token}:
    $ref: 'users.yaml#/paths/EmailConfirm'
  /users/{id}:
    $ref: 'users.yaml#/paths/GetOrUpdateUser'
  /users/{id}/avatar:
    $ref: 'users.yaml#/paths/GetOrUpdateAvatar'
  /users/{id}/promote:
    $ref: 'users.yaml#/paths/PromoteUser'
  /data:
    $ref: 'data.yaml#/paths/NewDatum'
  /data/{id}:
    $ref: 'data.yaml#/paths/GetOrUpdateDatum'
  /tests:
    $ref: 'tests.yaml#/paths/NewTest'
  /tests/{id}:
    $ref: 'tests.yaml#/paths/GetTest'
  /search:
    $ref: 'search.yaml#/paths/Search'

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: api.handlers.auth.check_token
